# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8acc8b14de0d4405b6d79d6efd2297fc1fb5d56fc5a1e568c3eb54cac3275f4f5b653760bdfc5521803160aa1a3b6460f30fee24a3290626d35ddc55de701e0f

test:
  secret_key_base: fc6c5b31f0428d2357aef4c3e862827715e89e6640ffc4ff0fcf2b02a565cb13825a0ace3745d0e03407ee3893230da094bf7486ae5189c0a8872d733856a3f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
